apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret-new
  annotations:
    kubernetes.io/dockerconfigjson: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJaR1ZsY0dscloybDBPbWRvY0Y4NVEwSmlVV0pVVDJ4bWVXUkJlWFJSWm1kdGJsazFhazVwVkhwRlJHZ3pjVGRJVUdvPSIKCQl9Cgl9Cn0=
